/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import query.jDlgMbsConsultaCompra;
import query.jDlgMbsConsultaFornecedor;
import query.jDlgMbsConsultaFuncionario;
import query.jDlgMbsConsultaProduto;
import query.jDlgMbsConsultaUsuarios;

/**
 *
 * @author marcelbenitezdasilva
 */
public class jFrmMbsPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public jFrmMbsPrincipal() {
        initComponents();
        setTitle("Sistema de Compras de Instrumentos Musicais");
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnUsuarios = new javax.swing.JButton();
        jBtnFornecedor = new javax.swing.JButton();
        jBtnCompras = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuPrincipal = new javax.swing.JMenu();
        jMnuFornecedores = new javax.swing.JMenuItem();
        jMnuFuncionarios = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuCompras = new javax.swing.JMenuItem();
        jMnuConsultas = new javax.swing.JMenu();
        jMnuUsuariosConsulta = new javax.swing.JMenuItem();
        jMnuProdutoConsulta = new javax.swing.JMenuItem();
        jMnuFuncionarioConsulta = new javax.swing.JMenuItem();
        jMnuFornecedorConsulta = new javax.swing.JMenuItem();
        jMnuComprasConsulta = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/instrumentaliza logo.jpg"))); // NOI18N

        jToolBar1.setRollover(true);

        jBtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png"))); // NOI18N
        jBtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnUsuarios);

        jBtnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedores.png"))); // NOI18N
        jBtnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFornecedorActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnFornecedor);

        jBtnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jBtnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComprasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnCompras);

        jMnuPrincipal.setText("Principal");
        jMnuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPrincipalActionPerformed(evt);
            }
        });

        jMnuFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedores.png"))); // NOI18N
        jMnuFornecedores.setText("Fornecedores ");
        jMnuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFornecedoresActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuFornecedores);

        jMnuFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        jMnuFuncionarios.setText("Funcionarios");
        jMnuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFuncionariosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuFuncionarios);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos_2.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuProdutos);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png"))); // NOI18N
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuUsuarios);
        jMnuPrincipal.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuSair);

        jMenuBar1.add(jMnuPrincipal);

        jMnuMovimento.setText("Movimento");

        jMnuCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jMnuCompras.setText("Compras");
        jMnuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuComprasActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuCompras);

        jMenuBar1.add(jMnuMovimento);

        jMnuConsultas.setText("Consultas");

        jMnuUsuariosConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png"))); // NOI18N
        jMnuUsuariosConsulta.setText("Usuarios");
        jMnuUsuariosConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuUsuariosConsulta);

        jMnuProdutoConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos_2.png"))); // NOI18N
        jMnuProdutoConsulta.setText("Produto");
        jMnuProdutoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutoConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuProdutoConsulta);

        jMnuFuncionarioConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        jMnuFuncionarioConsulta.setText("Funcionario");
        jMnuFuncionarioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFuncionarioConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuFuncionarioConsulta);

        jMnuFornecedorConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedores.png"))); // NOI18N
        jMnuFornecedorConsulta.setText("Fornecedor");
        jMnuFornecedorConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFornecedorConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuFornecedorConsulta);

        jMnuComprasConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jMnuComprasConsulta.setText("Compras");
        jMnuComprasConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuComprasConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuComprasConsulta);

        jMenuBar1.add(jMnuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        jDlgMbsUsuarios jDlgMbsUsuarios = new jDlgMbsUsuarios(null, true);
        jDlgMbsUsuarios.setVisible(true);       
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        jDlgMbsProdutoNovo jDlgMbsProdutoNovo = new jDlgMbsProdutoNovo(null, true);
        jDlgMbsProdutoNovo.setVisible(true);     
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFornecedoresActionPerformed
        // TODO add your handling code here:
        jDlgMbsFornecedor jDlgMbsFornecedor = new jDlgMbsFornecedor(null, true);
        jDlgMbsFornecedor.setVisible(true);     
    }//GEN-LAST:event_jMnuFornecedoresActionPerformed

    private void jMnuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuComprasActionPerformed
        // TODO add your handling code here:
        jDlgMbsCompra jDlgMbsCompra = new jDlgMbsCompra(null, true);
        jDlgMbsCompra.setVisible(true);
        
    }//GEN-LAST:event_jMnuComprasActionPerformed

    private void jMnuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuPrincipalActionPerformed

    private void jMnuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFuncionariosActionPerformed
        // TODO add your handling code here:
        jDlgMbsFuncionarioNovo jDlgMbsFuncionarioNovo = new jDlgMbsFuncionarioNovo(null, true);
        jDlgMbsFuncionarioNovo.setVisible(true);  
    }//GEN-LAST:event_jMnuFuncionariosActionPerformed

    private void jMnuUsuariosConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosConsultaActionPerformed
        // TODO add your handling code here:
        jDlgMbsConsultaUsuarios jDlgMbsConsultaUsuarios = new jDlgMbsConsultaUsuarios(null, true);
        jDlgMbsConsultaUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosConsultaActionPerformed

    private void jMnuFuncionarioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFuncionarioConsultaActionPerformed
        // TODO add your handling code here:
        jDlgMbsConsultaFuncionario jDlgMbsConsultaFuncionario = new jDlgMbsConsultaFuncionario(null, true);
        jDlgMbsConsultaFuncionario.setVisible(true);
    }//GEN-LAST:event_jMnuFuncionarioConsultaActionPerformed

    private void jMnuProdutoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutoConsultaActionPerformed
        // TODO add your handling code here:
        jDlgMbsConsultaProduto jDlgMbsConsultaProduto = new jDlgMbsConsultaProduto(null, true);
        jDlgMbsConsultaProduto.setVisible(true);
    }//GEN-LAST:event_jMnuProdutoConsultaActionPerformed

    private void jMnuFornecedorConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFornecedorConsultaActionPerformed
        // TODO add your handling code here:
        jDlgMbsConsultaFornecedor jDlgMbsConsultaFornecedor = new jDlgMbsConsultaFornecedor(null, true);
        jDlgMbsConsultaFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuFornecedorConsultaActionPerformed

    private void jBtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUsuariosActionPerformed
        // TODO add your handling code here:
        jDlgMbsConsultaUsuarios jDlgMbsConsultaUsuarios = new jDlgMbsConsultaUsuarios(null, true);
        jDlgMbsConsultaUsuarios.setVisible(true);
    }//GEN-LAST:event_jBtnUsuariosActionPerformed

    private void jBtnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFornecedorActionPerformed
        // TODO add your handling code here:
        jDlgMbsConsultaFornecedor jDlgMbsConsultaFornecedor = new jDlgMbsConsultaFornecedor(null, true);
        jDlgMbsConsultaFornecedor.setVisible(true);
    }//GEN-LAST:event_jBtnFornecedorActionPerformed

    private void jBtnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComprasActionPerformed
        // TODO add your handling code here:
        jDlgMbsCompra jDlgMbsCompra = new jDlgMbsCompra(null, true);
        jDlgMbsCompra.setVisible(true);
    }//GEN-LAST:event_jBtnComprasActionPerformed

    private void jMnuComprasConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuComprasConsultaActionPerformed
        // TODO add your handling code here:
        jDlgMbsConsultaCompra jDlgMbsConsultaCompra = new jDlgMbsConsultaCompra(null, true);
        jDlgMbsConsultaCompra.setVisible(true);
    }//GEN-LAST:event_jMnuComprasConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmMbsPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmMbsPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmMbsPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmMbsPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmMbsPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCompras;
    private javax.swing.JButton jBtnFornecedor;
    private javax.swing.JButton jBtnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMnuCompras;
    private javax.swing.JMenuItem jMnuComprasConsulta;
    private javax.swing.JMenu jMnuConsultas;
    private javax.swing.JMenuItem jMnuFornecedorConsulta;
    private javax.swing.JMenuItem jMnuFornecedores;
    private javax.swing.JMenuItem jMnuFuncionarioConsulta;
    private javax.swing.JMenuItem jMnuFuncionarios;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenu jMnuPrincipal;
    private javax.swing.JMenuItem jMnuProdutoConsulta;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuUsuariosConsulta;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
