package bean;
// Generated 12/09/2023 11:13:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MbsFuncionario generated by hbm2java
 */
@Entity
@Table(name="mbs_funcionario"
    ,catalog="db_marcel_silva"
)
public class MbsFuncionario  implements java.io.Serializable {


     private int mbsIdFuncionario;
     private String mbsNome;
     private String mbsEndereco;
     private String mbsCpf;
     private String mbsApelido;

    public MbsFuncionario() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mbs_idFuncionario", unique=true, nullable=false)
    public int getMbsIdFuncionario() {
        return this.mbsIdFuncionario;
    }
    
    public void setMbsIdFuncionario(int mbsIdFuncionario) {
        this.mbsIdFuncionario = mbsIdFuncionario;
    }

    
    @Column(name="mbs_nome", nullable=false, length=45)
    public String getMbsNome() {
        return this.mbsNome;
    }
    
    public void setMbsNome(String mbsNome) {
        this.mbsNome = mbsNome;
    }

    
    @Column(name="mbs_endereco", nullable=false, length=45)
    public String getMbsEndereco() {
        return this.mbsEndereco;
    }
    
    public void setMbsEndereco(String mbsEndereco) {
        this.mbsEndereco = mbsEndereco;
    }

    
    @Column(name="mbs_cpf", nullable=false, length=14)
    public String getMbsCpf() {
        return this.mbsCpf;
    }
    
    public void setMbsCpf(String mbsCpf) {
        this.mbsCpf = mbsCpf;
    }

    
    @Column(name="mbs_apelido", nullable=false, length=45)
    public String getMbsApelido() {
        return this.mbsApelido;
    }
    
    public void setMbsApelido(String mbsApelido) {
        this.mbsApelido = mbsApelido;
    }




}


