package bean;
// Generated 12/09/2023 11:13:53 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MbsUsuarios generated by hbm2java
 */
@Entity
@Table(name="mbs_usuarios"
    ,catalog="db_marcel_silva"
)
public class MbsUsuarios  implements java.io.Serializable {


     private int mbsIdUsuario;
     private String mbsNome;
     private String mbsApelido;
     private String mbsCpf;
     private Date mbsDataNascimento;
     private String mbsSenha;
     private int mbsNivel;
     private String mbsAtivo;

    public MbsUsuarios() {
    }

	
    public MbsUsuarios(String mbsNome, String mbsApelido, String mbsCpf, String mbsSenha, int mbsNivel, String mbsAtivo) {
        this.mbsNome = mbsNome;
        this.mbsApelido = mbsApelido;
        this.mbsCpf = mbsCpf;
        this.mbsSenha = mbsSenha;
        this.mbsNivel = mbsNivel;
        this.mbsAtivo = mbsAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mbs_idUsuario", unique=true, nullable=false)
    public int getMbsIdUsuario() {
        return this.mbsIdUsuario;
    }
    
    public void setMbsIdUsuario(int mbsIdUsuario) {
        this.mbsIdUsuario = mbsIdUsuario;
    }

    
    @Column(name="mbs_nome", nullable=false, length=60)
    public String getMbsNome() {
        return this.mbsNome;
    }
    
    public void setMbsNome(String mbsNome) {
        this.mbsNome = mbsNome;
    }

    
    @Column(name="mbs_apelido", nullable=false, length=25)
    public String getMbsApelido() {
        return this.mbsApelido;
    }
    
    public void setMbsApelido(String mbsApelido) {
        this.mbsApelido = mbsApelido;
    }

    
    @Column(name="mbs_cpf", nullable=false, length=14)
    public String getMbsCpf() {
        return this.mbsCpf;
    }
    
    public void setMbsCpf(String mbsCpf) {
        this.mbsCpf = mbsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mbs_dataNascimento", length=10)
    public Date getMbsDataNascimento() {
        return this.mbsDataNascimento;
    }
    
    public void setMbsDataNascimento(Date mbsDataNascimento) {
        this.mbsDataNascimento = mbsDataNascimento;
    }

    
    @Column(name="mbs_senha", nullable=false, length=20)
    public String getMbsSenha() {
        return this.mbsSenha;
    }
    
    public void setMbsSenha(String mbsSenha) {
        this.mbsSenha = mbsSenha;
    }

    
    @Column(name="mbs_nivel", nullable=false)
    public int getMbsNivel() {
        return this.mbsNivel;
    }
    
    public void setMbsNivel(int mbsNivel) {
        this.mbsNivel = mbsNivel;
    }

    
    @Column(name="mbs_ativo", nullable=false, length=1)
    public String getMbsAtivo() {
        return this.mbsAtivo;
    }
    
    public void setMbsAtivo(String mbsAtivo) {
        this.mbsAtivo = mbsAtivo;
    }




}


